version: '3.8'

services:
  postgres:
    container_name: postgres_ozon_task
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: posts
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  task-service:
    build: 

      dockerfile: ./Dockerfile
    container_name: post_ozon_task
    environment:
      STORAGE_TYPE: postgres
      DB_HOST: postgres
    depends_on:
      postgres:
        condition: 'service_healthy'
    ports:
      - 8080:8080